pipeline:
  buld_and_deploy:
    image: node
    pull: true
    commands:
      - pwd
      - yarn install
      - rm -rf build
      - git pull origin master
      - ./node_modules/gulp/bin/gulp.js default
      - rm -rf $CI_WORKSPACE
    when:
      branch: master
