pipeline:
  initial_setup:
    image: node
    pull: true
    commands:
      - yarn global add gulp-cli
    when:
      branch: master
  buld_and_deploy:
    image: node
    pull: true
    commands:
      - gulp
    when:
      branch: master