pipeline:
  buld_and_deploy:
    image: node
    pull: true
    commands:
      - yarn install
      - git pull origin master
      - ./node_modules/gulp/bin/gulp.js default
    when:
      branch: master
