before_script:
  - source ~/.bashrc

deployUat:
  stage: build
  only:
    - master
  tags:
    - macmini-drcleaner
  script:
    - yarn install
    - yarn build
    - scp -i "~/pems/passontw.pem" -r ./build/** $ACCOUNT@$UAT_HOST:$TARGET


